### ISSUE TITLE
Backgrounds resetting to default after switching profiles

### ISSUE THREAD

**Issue by Toweliechaos** [MikeSiLVO/skin.aeon.nox.silvo#181]
I have two profiles on my kodi setup. They have separate sources etc. For some inexplicable reason, when I change from one profile to the other, the background for certain menu items changes to the default image. In the skin settings however, it shows the image source as being something else (i.e. what I set it to). For my profile, it changes 'Addons' and 'Exit' menus (but not 4 others) and on the other, just 'Exit' (3 others left). The backgrounds are set to 'multi image' from a folder on attached ssd. I have tried resetting, changing the images and other things. But every time I change profile, it happens, even if it's days between using one profile and the other.

**Comment by MikeSiLVO** [comment]
Please use the [Kodi forum](https://forum.kodi.tv/index.php) for support.

**Comment by Toweliechaos** [comment]
Telling me it's a profile bug and not a skin bug would have been helpful in the original response rather than just making it look like you were shoving it onto someone else's plate. ;)

**Comment by MikeSiLVO** [comment]
I'm sorry. I must've missed the part where I work for you. 

Seek support on Kodi forum for an issue related to Kodi seems to make perfect sense if thought about for more than 2 seconds without assumption.

Sheesh

**Comment by Toweliechaos** [comment]
Hang on, the issue is on the skin background. Why would I assume that's a Kodi issue? I set the backgrounds in the Aeon Nox settings screens. All I'm saying is a simple "I'm closing this as it's actually an issue with Kodi, not the skin" is all it required.

**Comment by MikeSiLVO** [comment]
And I understand that but I was just going through old issues and copy pasting a response to clear them out.
As you can see I don't often get around to GitHub issues since I am usually busy on the forums, updating skins, or elsewhere doing real life stuff. 

If there had been a follow up question instead of saying I'm passing it off, I would have answered.

I try my best to help where and when I can but for me the forums is the best to reach me regularly.

**Comment by Toweliechaos** [comment]
Oh, I see you mean ask on your thread in the Kodi forum, not the general autocratic mess that is the forum in general? Understood now. Sorry, I have quite the beef with that place in general and probably over-reacted at being told to go there!
