### ISSUE TITLE
All titles in TV lists suddenly have the continuous sign ">>"

### ISSUE THREAD

**Issue by SubEdict** [MikeSiLVO/skin.aeon.nox.silvo#192]
Hi Mike
After the latest update (today)
1. All titles in TV lists suddenly have the continuous sign ">>" 
2. Default view suddenly shows as Right List (instead of List).

*Restart didn't help.

Screenshots:
https://imgur.com/a/HBMJRm8

PC, Win10, Kodi 20.2 - 21 beta 2 nightly.

**Comment by MikeSiLVO** [comment]
Do you have a screenshot showing how it used to look?

As for RightList being the default view... Use the view type selector to choose the default view. If script.skinvariables is installed it will build an include using the defaults in the viewtype builder json file.

**Comment by SubEdict** [comment]
>Do you have a screenshot showing how it used to look?

Without the ">>" on all the checkboxes. The checkbox is usually empty or "v" (finished watching all episodes).

>Use the view type selector to choose the default view.

OK, yep, found it. fixed. 👍 
Why the default view (TV/Episodes/Movies) change to RightView? It was always List.

**Comment by SubEdict** [comment]
Great, works! Thanks a lot. 👍
