### ISSUE TITLE
information line at bottom of screen

### ISSUE THREAD

**Issue by ib1ub12** [MikeSiLVO/skin.aeon.nox.silvo#193]
Hi since the recent update, the information line at the bottom of the screen has changed. When u want to pause or stop or fast-forward etc it looks cheap and boxy (sorry) is there any easy way to get it back to how it was?  Here is a pic of how it is now.  Cheers
![20231222_075532 1](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/25190924/c11a35af-1fe5-4932-92b8-312cea1d0b64)

**Comment by MikeSiLVO** [comment]
No
