### ISSUE TITLE
Movies/series playlists statistics not working on home screen anymore after 9.1.0

### ISSUE THREAD

**Issue by McRam** [MikeSiLVO/skin.aeon.nox.silvo#194]
After the 9.1.0 update the infoline on the home menu for movie and tv show items based on a playlist no longer displays any information.  See image below.

![image](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/6214441/1351c1de-482e-466e-8835-63d8e4848dc9)

The menu item has not changed. See image below.

![image](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/6214441/c61801ec-ce2d-4cb2-8a2c-a352ebb28d28)

Love your version of the Nox skin. Have been using this for a long time. Hope this can get fixed.

**Comment by MikeSiLVO** [comment]
If you are going to post an issue on GitHub then first read the What's new section in the add-on info of the skin or [this line from the addon.xml](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/blob/master/addon.xml#L102) please and thanks 😄
