### ISSUE TITLE
Resume(?) icons (double right facing blue arrows) showing on all Shows.

### ISSUE THREAD

**Issue by Better-Red** [MikeSiLVO/skin.aeon.nox.silvo#196]
Hi, thanks for all you do and I hope you're having a great Christmas.

Since the updates, resume icons (double right facing blue arrows) are showing on all Shows, regardless of whether I'm logged into Trakt or not, and whether I've watched the show or not.

Messing around, I tried both Kodi 20.2 Nexus (Aeon Nox Silvo 9.1.0) and Kodi 21.0 Omega Beta 2 (Aeon Nox Silvo 9.99.0) on both Android and Windows. I switched skins to Estuary which fixed the problem, I went back to Aeon Nox Silvo and the problem returned. I then reinstalled Aeon Nox Silvo (keeping the data) but it didn't help. Rolling back to the previous Kodi 20.2 version fixed it.

I've seen several others report the same issue on Reddit. Hopefully it's not difficult to fix and thanks again.

**Comment by MikeSiLVO** [comment]
This should already be fixed. If it is not then please provide screenshots from the latest Git version.
Thanks :)

**Comment by Better-Red** [comment]
Just tried on Kodi 20 Nexus and Kodi 21 Omega and confirm it's fixed. Much appreciated! Do you know if/when the versions will be bumped in the repo?

**Comment by andrewhulse1981** [comment]
Hi. Had the same issue so followed the steps to install the latest GitHub version and now that has removed any icon. Like before it had a number to says how many episodes left I had not watched or a tick next to a completed season. Is there anyway if this being added back in?

in the screen shot below i have watched all of season 1 but as you can see there is no tick
![1819D36D-C000-46A4-AA30-A62BACA55DC6](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/80646237/1828188f-59fa-4810-a5af-fa3f1ea90c0d)

**Comment by MikeSiLVO** [comment]
All of this should be fixed. 
If not please open an new issue

**Comment by Better-Red** [comment]
> All of this should be fixed. If not please open a new issue

Thanks @MikeSiLVO
