### ISSUE TITLE
Views no longer per source but only per content type?

### ISSUE THREAD

**Issue by thatso** [MikeSiLVO/skin.aeon.nox.silvo#197]
I'm on Kodi Nexus v20.2 and since your latest update v9.1.0 views can no longer be set per source.
I have several sources defined in Kodi representing different subfolders for video clips and set the content type for all of them to `movies` with no scraper assigned.
In the past, I could select different views for every source, i.e. `List` for `Videos1` and `Wall` for `Videos2`.
Since the last update, setting the view of one of these folders inherits it to all other folders of the same content type. If I set `List` for `Videos1`, `Videos2` will also have `List`. Changing `Videos2` to `Wall` results in `Videos1` showing as `Wall`.
Is this behavior intended?

**Comment by MikeSiLVO** [comment]
That is the way the skin variable addon works. If it is not installed or enabled then the old way still functions like it used to.

**Comment by thatso** [comment]
I have script.skinvariables 0.2.5 installed and enabled. Could you please elaborate what you mean with old way? Shall I disable this addon?

**Comment by MikeSiLVO** [comment]
You asked about "views no longer per source". That is what I mean by the old way. You could try to update Skin Variables using jurialmunkey's alpha repo and see if it gives more control but I don't know the differences between the two versions. 

Old way = the whole point of your post

New way = use script.skinvariables add-on to force a viewtype

**Comment by thatso** [comment]
For future readers: I simply uninstalled the script.skinvariables addon to get my views back. No other action required.
