### ISSUE TITLE
Movie submenu "in progress" not working after update

### ISSUE THREAD

**Issue by bootsmann** [MikeSiLVO/skin.aeon.nox.silvo#198]
Hi
Movies submenu "in progress" seems to be broken (). TV Shows "in progress" still working.

Running on LibreELEC-RPi4.arm-11.0.4

**Comment by MikeSiLVO** [comment]
Go into main menu setup and delete the in progress submenu item and then use the restore button to put it back.

**Comment by bootsmann** [comment]
Unfortunately it does not work. See attached pics. 
![aeon_silvo1](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/5744853/87fd2358-7fbc-4bb2-87ba-fa67306b1ee6)
![screenshot00012](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/5744853/dbe93d2d-bcd0-4c9b-a49f-4ea294f86245)
![screenshot00013](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/5744853/be0dbe02-3668-4323-8239-0e10c888e3d4)
