### ISSUE TITLE
Disable rating

### ISSUE THREAD

**Issue by psonnosp** [MikeSiLVO/skin.aeon.nox.silvo#201]
Hi and thanks for a great skin.

Would it be possible to add a setting to disable MPAA rating?
I don't care for it and never scrape it so I have that NR logo on everything and it's kind of annoying and pointless.

If it's to much work  to add it, can I change something in a file somewhere to make it disappear?

**Comment by psonnosp** [comment]
@MikeSiLVO 
How about my question if my request was denied? Can I "easily" change some parameters in a file somewhere to make it disappear? I've solved it by changing the image to a blank one but that is kind of time-consuming plus I have to redo it every time the skin updates.

**Comment by MikeSiLVO** [comment]
Easiest solution would be to use the GitHub version of the skin which doesn't have a Textures.xbt file and either delete the NR image or use a blank one and rename it NR.png.

Like this [one](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/blob/master/media/colors/blank.png)

**Comment by MikeSiLVO** [comment]
Are you using a PC?

**Comment by MikeSiLVO** [comment]
What about me adding blank as possible mpaa field or something similar?

Then you could maybe mass update your library using the matching string so the variable will show the blank image i linked to earlier?
