### ISSUE TITLE
Push rating changes to nfo

### ISSUE THREAD

**Issue by MCSmarties** [MikeSiLVO/skin.aeon.nox.silvo#202]
The skin contains a very convenient option to "Set my rating" by simply clicking on the "star" icon. 
![no update](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/156861250/1a48350c-e9ec-4142-b8a2-830f06b6674c)

Unfortunately however, this added/changed rating is not updated in the corresponding .nfo file.

Yet interestingly, going through the more laborious option of clicking on hamburger menu -> Edit immediately reflects all changes (including "User rating") to the .nfo:
![update1](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/156861250/57331bd0-3d10-4f93-89aa-14fc451786ac)
![update2](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/156861250/fd0cb834-a249-4aef-834d-3c338228be18)
![nfo](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/156861250/79515d67-973a-464f-a2c7-5ec3a0911002)

**Is this a bug, or is there a particular reason why using the "star" results in a different behavior?**

Thank you so much for your hard work, your skin is what makes Kodi really worthwile to use!

(Using v 9.1.2 on Nexus v20-33 2024-01-10 , but I noticed this odd behavior already on with Matrix)

**Comment by MikeSiLVO** [comment]
The star icon is Kodi's built in way to set a personal rating. I assume if you exported your library to nfo it would update but that is Kodi-related and not something the skin can control.

Edit is using script.metadata.editor and I believe you have to enable 'write to nfo' in its settings for it to do that.

**Comment by MCSmarties** [comment]
Thanks a lot for replying, much appreciated! I know that I can export the library to nfo with kodi, but in my experience it's not a reliable process, it often corrupts my files. So I avoid using that.

Guess my question then becomes: is there a way to make the star icon use script.metadata.editor (if it is installed), and use the built-in Kodi way if not?

**Comment by MikeSiLVO** [comment]
According to the scripts wiki there is a way to call the set rating directly but I am not sure if I will add it to the skin. Too many people lose their collective minds when things suddenly change. Nobody reads the What's new so then it becomes an extremely annoying thing for me to deal with...
