### ISSUE TITLE
Mpaa French ratings provided by Jellyfin

### ISSUE THREAD

**Issue by Philmo67** [MikeSiLVO/skin.aeon.nox.silvo#203]
Hello,
since Jellyfin used as a backend prefixes mpaa ratings with its countrycode and an hyphen, would it be possible to alter Variables.xml like this ?
`<value condition="String.Contains(ListItem.MPAA,France:U) | String.Contains(ListItem.MPAA,Tout public) | String.Contains(ListItem.MPAA,FR-U) | String.Contains(ListItem.MPAA,FR-TP) | String.Contains(ListItem.MPAA,partir de 3 ans) | String.Contains(ListItem.MPAA,partir de 6 ans)">csaU.png</value>
<value condition="String.Contains(ListItem.MPAA,France:-10) | String.Contains(ListItem.MPAA,Interdit aux moins de 10 ans) | String.Contains(ListItem.MPAA,FR-10) | String.Contains(ListItem.MPAA,des propos ou des images peuvent heurter)">csa10.png</value>
<value condition="String.Contains(ListItem.MPAA,France:-12) | String.Contains(ListItem.MPAA,Interdit aux moins de 12 ans) | String.Contains(ListItem.MPAA,FR-12)">csa12.png</value>
<value condition="String.Contains(ListItem.MPAA,France:-16) | String.Contains(ListItem.MPAA,Interdit aux moins de 16 ans) | String.Contains(ListItem.MPAA,FR-16)">csa16.png</value>
<value condition="String.Contains(ListItem.MPAA,France:-18) | String.Contains(ListItem.MPAA,Interdit aux moins de 18 ans) | String.Contains(ListItem.MPAA,FR-18)">csa18.png</value>`
(Tested OK with my kodi instance)

**Comment by MikeSiLVO** [comment]
Can you break this down to just the additions please?

**Comment by Philmo67** [comment]
Sure : 

- add "| String.Contains(ListItem.MPAA,FR-U) | String.Contains(ListItem.MPAA,FR-TP)" for csaU.png
- add "| String.Contains(ListItem.MPAA,FR-10)" for csa10.png
- add "| String.Contains(ListItem.MPAA,FR-12)" for csa12.png
- add "| String.Contains(ListItem.MPAA,FR-16)" for csa16.png
- add "| String.Contains(ListItem.MPAA,FR-18)" for csa18.png
