### ISSUE TITLE
Enable Bluray3D media flag for media stubs

### ISSUE THREAD

**Issue by Philmo67** [MikeSiLVO/skin.aeon.nox.silvo#204]
Hello,
in order to enable bluray3d media flag for media stubs (*.disc files) that cannot have stereographic metadata, would it be possible to alter Variables.xml like this ?
`
<variable name="SourceFlagVar">
		<value condition="[String.Contains(ListItem.Filename,3d) | String.Contains(ListItem.Filename,3dbd) | ListItem.IsStereoscopic]">bluray3d.png</value>
`
and
`
<variable name="VideoSourceFlagVar">
		<value condition="[String.Contains(ListItem.Filename,3d) | String.Contains(ListItem.Filename,3dbd) | ListItem.IsStereoscopic]">bluray3d.png</value>
`
(Tested OK with my kodi instance)

**Comment by MikeSiLVO** [comment]
The problem I have with this is false positives. Filename additions could say anything and be completely inaccurate. Probing the file for information is not.

There a few examples of movies but off the top of my head Jaws 3 is usually referred to as Jaws 3D in this case it would wrongly be classified as 3-D when not.

I am not sure of a middle ground here since most users of the skin either rip content to HDD in a container like mkv or stream it...

**Comment by Philmo67** [comment]
Maybe a solution without false positives could be to test "3d" and its mode : sbs, tab or mvc ?
See https://kodi.wiki/view/3D

**Comment by MikeSiLVO** [comment]
Doesn't using Kodi naming convention solve your issue?

If you name it that way then Kodi should mark it as stereoscopic, no?

**Comment by Philmo67** [comment]
That is exactly what I did and without the "String.Contains(ListItem.Filename..." clauses I added, no 3D flag can be displayed for a filestub.
Actually, only the "isstereoscopic" flag is tested, not the filename in order to display the bluray3d.png logo

So maybe filename should be tested against : 
3d.mvc
3d.sbs
3d.hsbs
3d.fsbs
3d.tab
3d.htab
3d.ftab
3d-mvc
3d-sbs
3d-hsbs
3d-fsbs
3d-tab
3d-htab
3d-ftab
3d_mvc
3d_sbs
3d_hsbs
3d_fsbs
3d_tab
3d_htab
3d_ftab
in order to avoid false positives ?

**Comment by Philmo67** [comment]
Actualy KODI wiki states : 

> Kodi uses regular expressions to check for certain flags in the filename.

In order to properly detect the stereomode, two tags need to be present in the filename. First, a '3D' tag has to be present that matches the following regex: [-. _]3d[-. _]

In addition to this, either a 'SBS' tag [-. _]h?sbs[-. _] or a 'TAB' flag [-. _]h?tab[-. _] must be present in the filename.

**Comment by MikeSiLVO** [comment]
What about trying what [this person did](https://forum.kodi.tv/showthread.php?tid=376716)?
Also [HERE](https://forum.kodi.tv/showthread.php?tid=376851)

https://kodi.wiki/view/NFO_files/Combination
