### ISSUE TITLE
Player skin

### ISSUE THREAD

**Issue by audiosistem** [MikeSiLVO/skin.aeon.nox.silvo#205]
Hello! Is it possible, in a future update, to go back to the previous graphics of the player(OSD)? Thank you!

**Comment by RowanDDR** [comment]
Disagree. Old ones seem a bit dated - skeuomorphism peaked like 16 years ago? I prefer the new plain style, they look more contemporary.

**Comment by Better-Red** [comment]
I like the new icons and graphics. Some people cannot cope with change.

**Comment by audiosistem** [comment]
No problem! Have a good day!
