### ISSUE TITLE
Bugs in Live Backgrounds feature

### ISSUE THREAD

**Issue by davewuk** [MikeSiLVO/skin.aeon.nox.silvo#206]
I use Live Backgrounds for my Movies and Music main menus (like the original Aeon Nox from frodo/gotham era) and have noticed a couple of bugs in Aeon Nox Silvo in Nexus:-

1. When a live background has albums or songs as source the mesh background (default_livecases.jpg) is not displayed

2. When a live background has the skin built-in smart playlist "Random Albums" as a source, the CD cases are not displayed and the aspect ratio of the CD covers shown is incorrect, It works when the live background is set to "Random Albums" however.

3. There is no matching "Random Movies" to select from the drop-down but there is a skin smart playlist of the same name which works. This is inconsistent rather than a bug I guess.

I've fixed 1 and 3 locally by editing both Includes_LiveBG.xml and overrides.xml, see the diffs below. I'm not sure on 2 but there is something most likely not correct in the conditional that decides whether or not to display CD cases or DVD cases in Includes_LiveBG.xml

Includes_LiveBG.xml 
![Includes_LiveBG](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/55807111/84732f80-7f19-4124-881c-edacd683c942)

overrides.xml,
![overrides](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/55807111/6c96c18d-b815-4b2c-b78a-1ee0e3a22697)

I'm a (very) oldschool C++ coder and don't know how to use git otherwise I'd submit these as a PR

**Comment by davewuk** [comment]
Now that Omega is out I have updated to the latest version of this skin and backported my bug fixes and I've attached the two affected files below:

[Live Backgrounds Fix.zip](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/files/14919011/Live.Backgrounds.Fix.zip)

**Comment by MikeSiLVO** [comment]
I will add the background for albums and songs, and I will also include random movies as an option.

Thanks

For number 2 there is no way for me to check a playlist provided by skin shortcuts 
`<background label="Live Background: ::PLAYLIST::">s:live|i:playlist</background>` that just shows all available playlists both skin provided and user created. For music its best to choose one of the live background options that do not say 

> Video Playlist

 or 

> Skin Playlist.
