### ISSUE TITLE
TVShow Widget (Panel Extended) & EmbyNextGen: Not showing all series in dynamic nodes; not showing series titles in sync'd nodes.

### ISSUE THREAD

**Issue by serendrewpity** [MikeSiLVO/skin.aeon.nox.silvo#208]
Kodi: v 20.3
LibreELEC: v11.06
AeonNox SiLVO: v9.1.4
Emby Next-Gen: v9.4.15

I setup a home screen in Kodi for TV Shows.  Widget 2 is recently added episodes.  It works fine. No complaints. Also, movie widgets are fine.

Widget 1 is for all my TV series.  I use Emby Next-Gen.  I setup Widget 1, by selecting addons->videos addons->Emby for Kodi Next-Gen-> Dynamic Nodes (or Synced Nodes)-> TV Shows-> TV Shows.  I then select "Panel Extended".  The remainder of the settings are personal preference.  I've toggled them all with no effect on the issue I am describing here.  Except for one (more later).

The resulting widget using Dynamic Nodes only displays the first twenty-five TV series.  If I go back to the widget settings and change the widget "Limit to" value to 100, I can get it to display 100 TV series (it was set to 'none' when it displayed 25).   If I go back to the widget settings and use Synced Nodes, it will display all of my TV series, however when I select a series and open it, I only see a number where the episode title should be, that number seems to be ID number that range from 0 to 9999.

As it stands, I can only see the first 100 TV Series in this widget or I can see all of them, but not the episode titles. As a sanity check I switched over to the Embuary Skin as suggested on the Emby Support page, [here](https://emby.media/community/index.php?/topic/67653-episodes-showing-only-number-not-name/).    A user there was having the same issue five years ago.  The problem does not exist on Embuary and as indicated in the Emby Support page, this means its not an issue with Emby.  A 'regular' user there, suggeted the following: 

> "Sounds like the active window is music type rather than video."

I believe he is referring to the Synced Nodes showing an (ID) number as opposed episode titles. Help!?

**Comment by MikeSiLVO** [comment]
I don't use Emby so your best bet is to ask in the Emby forum, the Emby Next Gen forum wherever that may be, or the [Kodi forum](https://forum.kodi.tv/index.php).

Saulfred was talking about the target window for the onclick action.

You can edit any items action so if it says music and needs to be changed to videos, that is what was mentioned in that thread,  you can do that.
