### ISSUE TITLE
Feature Request: Displaying 4K/UHD Bluray Logos for UHD Blu-rays registered via stub files

### ISSUE THREAD

**Issue by Totopsgr** [MikeSiLVO/skin.aeon.nox.silvo#209]
Despite experimenting with stub filenames that include "4K", "UHD", "UHD Blu-ray", and "2160p", only the Blu-ray logo is shown.

I tried creating .nfo files for these files to address this, which successfully brought up the 4K logos. However, this approach means Kodi draws movie data exclusively from either the .nfo file or the scraper—never both. Consequently, I'm left choosing between having the 4K logo displayed or accessing the full suite of movie information collected from the internet, including posters, art, and ratings.

Please allow for logo display of 4K and or UHD Blu-ray logos, triggered by strings included in the filename such as "4K", "UHD", "BDXL", or any other preferred naming convention. Ideas for Logos that can be incorporated:

![image](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/58504152/aeb1fdd4-0f74-4f80-86fd-a9af724d3cbe)

![image](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/58504152/10b945d2-9520-4edf-8d1f-17d37ec75ef3)

![image](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/58504152/32dac126-2434-4f93-a133-f2712ed8a3e5)

For reference and if of any help, the only skin that I found that has implemented this is Rapier.

https://kodi.wiki/view/Add-on:Rapier

**Comment by MikeSiLVO** [comment]
Closing this since it appears you have this solved.
https://forum.kodi.tv/showthread.php?tid=376716
