### ISSUE TITLE
21 RC2 Status Indicators and Number of Unwatched Episodes

### ISSUE THREAD

**Issue by Jeffers24** [MikeSiLVO/skin.aeon.nox.silvo#210]
When I updated to 21 RC1 no issues.
When I updated to 21 RC2 a number of my skin settings were changed.
For example the Status Indicators in the Info Wall View were disabled.
Not a big issue I changed the setting to Enabled.
I now get a tick if all episodes are watched and a star if not all episodes are watched.
In Kodi 20, 21 Betas and 21 RC1 I the number of unwatched episodes also displayed. Now in 21 RC2 the number of unwatched episodes is not displayed.
Is there a new setting in 21 RC2 skin that I need to change?
![Screenshot_48](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/47518199/7dc56455-9795-4e6c-bf5c-413292529ce3)

**Comment by MikeSiLVO** [comment]
Works for me. Are you sure it's not disabled in the status indicators area. The unwatched count should work with the other indicators disabled.

![kodi_vLviSEtVNh](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/3333139/522fbd20-1b38-450f-b0c3-62127c792a31)

![screenshot00033](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/3333139/9652fd00-fb88-4d53-af72-c867be7c1245)

**Comment by Jeffers24** [comment]
Thanks Mike, I thought it would be a setting but couldn't remember where it was as I had copied my build into each Kodi upgrade, 19 to 20 then 21 Betas, then 21 RC1 without any issues. Then when I copied my build (portable folder (Kodi folder0 on my PC from RC1 portable install to RC2 portable install a number of my skin settings got unset, including the Unwatched episode count.
![Screenshot_49](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/47518199/17b8ad91-6e4f-436c-82f3-5aadfa77dd52)

**Comment by Jeffers24** [comment]
Unwatched episode count unset by copying build from RC1 to RC2, now reset thanks to Mike's help
