### ISSUE TITLE
OSD music

### ISSUE THREAD

**Issue by Slim1399** [MikeSiLVO/skin.aeon.nox.silvo#212]
Kodi: v 20.3
LibreELEC: v11.06
AeonNox SiLVO: v9.1.5

It don't longer processes jpg discart ! 

![screenshot00017](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/58898611/e08ecbd6-cd78-49ed-b860-94aa15101b9f)

**Comment by mchawk777** [comment]
Same here - testet the github-Version from today.

**Comment by MikeSiLVO** [comment]
Try reverting this [commit](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/commit/2f3164ca987b12cd57c270c6e8f61d5242d4b27e)

**Comment by Slim1399** [comment]
Thank you, but it's the same for all the views in there is a discart 
![screenshot00024](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/58898611/4be0be0d-8fdc-4e09-b775-3f9694ae096a)
![screenshot00022](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/58898611/a39b3aff-af2c-4160-a039-9bf1c8ba5e1a)

**Comment by MikeSiLVO** [comment]
Can't you use transparent png's for discart?

Someone requested that it be removed cause it removes some of the CD image when it already contains the transparent parts.

**Comment by Slim1399** [comment]
I have a large library, i mostly use png Discart but many only exist in jpg.

**Comment by MikeSiLVO** [comment]
Ok, good enough answer for me. I'll revert to and re-add the diffuse texture.

I'll close this issue, with a link to the commit, when its done.

**Comment by MikeSiLVO** [comment]
Reverted with 88f57d7

I'll also take a look at your PR's and add them if they are for the music section only.
