### ISSUE TITLE
Issues after Aeon Nox Silvo auto-updated to v10.0.2 LibreElec 12.0.0

### ISSUE THREAD

**Issue by thestraycat** [MikeSiLVO/skin.aeon.nox.silvo#217]
I'm running LibreElec 12.0.0 on RPI4b and have always ran Aeon Nox Silvo since when i can remember. 

Recently my installation gets stuck on ' Building Menus' after an update. I was watching a film and then the film suddently froze and the logs showed that Aeon Nox Silvo had updated. 

When i exitted to the main menu all my menus were broken and fonts changed and graphical elements missing.

After i rebooted i was stuck on the Building Menu's screen until the screen saver kicked in, the only way i could fix it was by using the web interface and then changing the skin back to Estuary.

The log was full of errors referencing Aeon Nox Silvo as well. 

Such as:

Unable to load window XML: /storage/.kodi/addons/skin.aeon.nox.silvo/16x9/DialogNotification.xml. Line 0
                                                   Failed to open file

Can you advise?

**Comment by MikeSiLVO** [comment]
Please use the [Kodi forum](https://forum.kodi.tv/index.php) for support but you'll need to post a debug log there for any assistance.

**Comment by thestraycat** [comment]
Thanks Mike. How do you know this is specifically a Kodi issue though and not Aeon Nox Silvo? As i detailed. I'd be running Aeon Nox Silvo for years, then the skin addon updated, then it broke. 

Is there a chance that this could be somehow connected to the recent LibreElec 12 releases?

**Comment by MikeSiLVO** [comment]
While I doubt it is the skin issue since Aeon Nox SiLVO is one of the top most downloaded skins. If there was an issue related to the skin updating then I'd think there would be a lot more posts about it. Many reasons for an update failure that are beyond my control. A reinstall usually fixes any problems.

Also I don't regularly provide support on GitHub. It is best to use the forums since I visit there almost daily.

**Comment by thestraycat** [comment]
OK, thanks. The Kodi Forums right? I frequenct the libreelec forums as thats what i run.
