### ISSUE TITLE
Seeking Bar in pvr channel

### ISSUE THREAD

**Issue by GTTech2305** [MikeSiLVO/skin.aeon.nox.silvo#218]
Hey new update version chanenl seeking bar get big and not able to see next program become it's overlap on the that and also it's show only one coler and not like what older version show progress of show or movie

**Comment by GTTech2305** [comment]
![17175250068612293170967259424964](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/103832559/d132848a-0a03-412d-9b3b-bfa20816066e)
![17175250441002325794180619696957](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/103832559/75a00633-44f2-4d18-b487-e01293f33f77)

**Comment by MikeSiLVO** [comment]
Fixed with latest commit

Thanks

**Comment by GTTech2305** [comment]
So it will be get fix in next update
And also once channel play EPG SHOW unknown word and logo not come

**Comment by MikeSiLVO** [comment]
It's fixed on GitHub now so you can [use that version](https://forum.kodi.tv/showthread.php?tid=210069&pid=1850231#pid1850231) or wait for the next update.

For all other issues, please seek support on the [Kodi forum](https://forum.kodi.tv/index.php).
