### ISSUE TITLE
V22 OSD - Subtitle Settings button missing

### ISSUE THREAD

**Issue by tom-shell** [MikeSiLVO/skin.aeon.nox.silvo#224]
Kodi v22-ALPHA1(20240806-31b16750ae) WebOS
Aeon Nox Silvo v10.0.3

When video in full screen is played and you enter OSD the "Subtitle Settings" (change subtitle, disable subtitle, set delay etc) button is missing.

The problem might affect Kodi V22 as there is another person reporting this issue on Kodi forum on Nvidia Shield, Android 11, Shield experience 9.1.1, Kodinerds 22 (see this [thread](https://forum.kodi.tv/showthread.php?tid=378196)).

Workaround is to map subtitle cycle button on your remote using Keymap editor.

**Comment by MikeSiLVO** [comment]
v22 is still in alpha and this is a Kodi bug rendering bug.

You can keep track of it here:
https://github.com/xbmc/xbmc/issues/25279

I am not doing any skin changes for alpha versions of Kodi, anything could break from commit to commit.
